### ISSUE TITLE
Firefox Add-on

### ISSUE THREAD

**Issue by JoshuaMurphynz** [Someguy123/HiddenEverywhere#10]
How often do you update the Firefox addon?

**Comment by Someguy123** [comment]
I try to get it updated as often as possible. At the moment I don't see any feature improvements needed (if you do, feel free to make an issue on here, or a pull request).

Note: Mozilla takes DAYS to review my updates. Yes, even though they're usually a SINGLE line added to urls.txt, it can take up to 3 days before it appears on the official site, and Firefox automatic add-on updates

Example: I just pushed out 0.1.2 to AMO, however, I'm in queue position 46, meaning 45 other add-ons have to be reviewed before your recent URL addition ends up in the live add-on.

**Comment by JoshuaMurphynz** [comment]
Alright fair enough. I hear you. Maybe try updating every month? Quite a lot of URLs have been added in the last 24 days.

**Comment by Someguy123** [comment]
not83: I've updated the add-on usually after every 1 or 2 issues. I believe the latest copy on Github is the same one that's live on AMO right now.

**Comment by JoshuaMurphynz** [comment]
Sweet
