### ISSUE TITLE
add repo.voidlinux.eu and build.voidlinux.eu

### ISSUE THREAD

**Issue by torthrowaway-ouSoi7ee** [Someguy123/HiddenEverywhere#29]
The onion addresses are:
- repo.voidlinux.eu:
  onion address: fd6dqrupy3af4xwb.onion
- build.voidlinux.eu:
  onion address: s7y2awkwau4nbdpu.onion

see http://www.voidlinux.eu/news/2016/08/Tor-Hidden-Service.html

**Comment by Someguy123** [comment]
Thanks for the suggestions, they're added now 👍
